SimonBoothroyd/nagl

nagl/cli/prepare/enumerate.py
nagl/tests/cli/prepare/test_enumerate.py

This PR updates the `enumerate` CLI to only save out unique tautomers.

Only Retain Unique Enumerated Tautomers

---

nagl/labels/am1.py

This PR ensures molecules have explicit hydrogens added before computing AM1 properties. This is needed when computing the WBOs otherwise OE will interpret some molecules as containing radicals.

Add Explicit Hydrogens When Computing AM1 Labels

---

nagl/cli/label/label.py
nagl/tests/utilities/test_provenance.py
nagl/utilities/provenance.py

This PR adds basic provenance information when to the molecule store created by running the label CLI.

Add Basic provenance to Labelled Molecule Store

---

.github/workflows/ci.yaml
devtools/conda-envs/test_env.yaml

This PR updates the CI to use the C-F `openff-toolkit` package now that 0.9.1 is released which contains the toolkit independent ELF implementations and API points.

Update the CI to use the C-F openff-toolkit package

---

nagl/utilities/rmsd.py

This PR ensures that the `openff.toolkit` module is a local import. This reduces the time to import `nagl` and leads to speedups when calling CLI methods - especially `nagl COMMAND --help`.

Make the OpenFF toolkit a local only import

---

nagl/utilities/smiles.py

This PR patches any issue whereby the OpenFF toolkit currently raises an exception for unidentified stereochemistry when loading molecules with pyramidal nitrogens using the OE backend, but  (correctly) does not return any stereoisomers when enumerating undefined stereochemistry.
This issue is tracked on the OpenFF issue tracker here: https://github.com/openforcefield/openff-toolkit/issues/725.

Temporary fix guessing stereochemistry of pyramidal N

---

nagl/dataset/dataset.py
nagl/tests/dataset/test_dataset.py

This PR adds a new `MoleculeGraphDataset.from_molecule_stores` class method which can create a data set from multiple molecule stores.
This method does not currently check if there is duplicate data in the provided stores.

Adds data set from molecule store function

---

nagl/cli/label/label.py
nagl/datasets.py
nagl/storage/db.py
nagl/storage/storage.py
nagl/tests/storage/test_storage.py

This PR simplifies the DB store by:
* removing individual tables for coordinates and charge / WBO values and instead just pickling the raw arrays.
* storing the InChI key rather than the hill formula to discriminate identical molecules using.

Simplify the molecule DB store

---

nagl/cli/label/label.py
nagl/tests/utilities/test_rmsd.py
nagl/tests/utilities/test_toolkits.py
nagl/utilities/rmsd.py
nagl/utilities/toolkits.py

This PR speeds up, by order of magnitudes in certain cases where there is a large number of topologically symmetrical atoms, comparing if two conformers are 'identical' within some tolerance.
This new algorithm makes use of atom symmetries to first try and optimally align the two conformers using a minimum number of atoms, and then performing a simple distance check once aligned. This removes the need to find all possible perturbations of atom ordering when trying to align the molecules.

Order of magnitudes speed up of conformer comparison

---

nagl/molecules.py
nagl/tests/test_molecules.py

This PR adds a `to` function to the `DGLMolecule*` classes so that `pytorch-lightning` can correctly move the data batches over to the requested devices.

Add `DGLMolecule` to device

---

nagl/cli/label/label.py
nagl/labelling.py
nagl/tests/test_labelling.py

This PR begins to generalise molecule labelling by moving the default label code from the CLI into a new module.

Split labelling into separate module

---

nagl/features.py
nagl/lightning.py
nagl/tests/test_features.py
nagl/tests/test_lightning.py

This PR adds a new general `DGLMoleculeDataModule` that tries to make loading in data stored in SQLite molecule stores more compact, e.g.
```
data_module = DGLMoleculeDataModule(
atom_features,
bond_features,
partial_charge_method="am1",
bond_order_method=None,
train_set_path="train.sqlite",
train_batch_size=512,
val_set_path="val.sqlite",
test_set_path="test.sqlite",
use_cached_data=True,
)
n_atom_features = data_module.n_atom_features
```

Add a general lightning data module

---

nagl/datasets.py
nagl/lightning.py
nagl/tests/test_datasets.py
nagl/tests/test_lightning.py

This PR ensures that resonance enumeration is now correctly exposed via the lightning data module constructor.

Expose resonance enumeration via data module

---

nagl/datasets.py
nagl/lightning.py
nagl/molecules.py
nagl/tests/nn/test_process.py
nagl/tests/resonance/test_conversion.py
nagl/tests/test_datasets.py
nagl/tests/test_lightning.py
nagl/tests/test_molecules.py

This PR replaces the `enumerate_resonance` argument taken by most functions that at some point convert an OpenFF molecule to a DGL molecule with a more flexible `molecule_to_dgl` callable, allowing users to perform whatever custom enumeration they would like.

Replace enumerate resonance arg with callable

---

nagl/resonance/_resonance.py
nagl/tests/resonance/test_resonance.py

This PR exposes a new `include_all_transfer_pathways` flag to the resonance enumeration utility that controls whether resonance forms are de-duplicated to ignore bond order prior to being returned.

Expose option to include all resonance transfer pathways

---

nagl/cli/prepare/enumerate.py
nagl/tests/cli/prepare/test_enumerate.py

This PR adds basic protonation state enumeration to the `nagl prepare enumerate` command:
```
nagl prepare enumerate --help                                          
Usage: nagl prepare enumerate [OPTIONS]
Enumerates all reasonable tautomers (as determine by the OpenEye toolkit)
of a specified set of molecules.
Options:
--input FILE                    The path to the input molecules. This should
either be an SDF or a GZipped SDF file.
[required]
--output FILE                   The path to save the enumerated molecules
to. This should either be an SDF or a
GZipped SDF file.  [required]
--tautomers / --no-tautomers    Whether to enumerate possible tautomers or
not.  [default: False]
--max-tautomers INTEGER         The maximum number of tautomers to generate
per input molecule.  [default: …
```

Add initial protomer enumeration support

---

examples/train-am1-q-model.py
nagl/utilities/toolkits.py

This PR disables the OE molecule normalization pathway for now. Currently the `OEUniMolecularRxn` method will only transfer bonds if they are explicitly provided in a SMILES pattern, which means certain single bonds don't have their bond order currectly update. E.g. `[N,P,As,Sb;X3:1](=[O,S,Se,Te:2])=[O,S,Se,Te:3]>>[*+1:1]([*-1:2])=[*:3]` does not explicitly state that the 1-2 bond should have a single bond after the 'reaction'.
Until the SMARTS patterns are re-written this code this path is disabled to avoid confusion and possible valence issues.

Disable OE molecule normalisation

---

nagl/cli/label/label.py

Expose the conformer RMS cutoff via the label CLI.

Expose conformer RMS through label CLI

---

nagl/storage/db.py

This PR is a first step in allowing entries to be deleted from a store, ensuring that all children of a molecule record are removed from the store when the parent record is.

Delete orphaned DB rows on record deletion

---

devtools/conda-envs/test_env.yaml
setup.cfg

It seems that `codecov` has started to include `tests` in the coverage report when it should be omitted. This PR aims to resolve this.

Omit tests in codecov report

---

.github/workflows/ci.yaml
devtools/conda-envs/test_env.yaml
nagl/lightning.py

This PR adds an extra loss function argument to the `DGLMoleculeLightningModel` allowing users to provide their own loss function for extra customisation rather than having to implement them all in nagl. 
Notable points that this PR has either accomplished or will accomplish.

Allow loss function customisation

---

nagl/features.py
nagl/tests/test_features.py

This PR allows users to register custom features defined outside of NAGL, and have them be useable from the model configuration object.
The API for this looks like:
```python
class MyAtomFeature(AtomFeature):
type: typing.Literal["some-type"] = "some-type"
def __call__(self, molecule: "Molecule") -> torch.Tensor:
return ...
def __len__(self):
return ...
register_atom_feature(MyAtomFeature)
```

Support external atom and bond features

---

devtools/envs/base.yaml
nagl/reporting/__init__.py
nagl/reporting/_reporting.py
nagl/reporting/template.html
nagl/tests/reporting/test_reporting.py
pyproject.toml

This PR adds a simple HTML report that shows predicted vs reference atom labels as well as computed metrics for a list of molecules.
Clicking on any of the images will open a pop-up with a larger, easier to read, image.

Add basic HTML report of predicted atom labels

---

nagl/datasets.py
nagl/reporting/_reporting.py
nagl/training/lightning.py

This PR ensures the correct batch size is passed to the data loader if ``None``, and turns off multiple workers which significantly slowed performance.

Fix lightning data module batch size and performance
